### ISSUE TITLE
相似项目 长江水情监测

### ISSUE THREAD

**Issue by cxumol** [Cloudiver/water_quality#1]
自荐我的类似项目, 长江水情监测｡ 出发点类似, 都是给公开的民用实时数据做历史存档｡ 
项目链接在此 https://github.com/cxumol/LongRiver
这里还多一些后续步骤, 比如数据处理 (json 转 csv, 便于在 github 上阅读) 和[数据可视化](https://cxumol.github.io/LongRiver/)  (绘制趋势图, 发表网页) 部分｡ 
希望能有启发｡

**Comment by Cloudiver** [comment]
@cxumol 谢谢分享, 有时间找你请教.
请问能通过哪些方式联系到你?

**Comment by cxumol** [comment]
不客气, 如有疑问也可以到我项目提 issue. 
可以在 telegram 上找到我, 用户名同名; 或电邮 cxumol#etlgr#com

**Comment by Cloudiver** [comment]
> 自荐我的类似项目, 长江水情监测｡ 出发点类似, 都是给公开的民用实时数据做历史存档｡
> 项目链接在此 https://github.com/cxumol/LongRiver
> 这里还多一些后续步骤, 比如数据处理 (json 转 csv, 便于在 github 上阅读) 和[数据可视化](https://cxumol.github.io/LongRiver/) (绘制趋势图, 发表网页) 部分｡
> 希望能有启发｡

把存储格式改为csv了。[water_quality_by_name](https://github.com/Cloudiver/water_quality/tree/master/water_quality_by_name)
前端不熟，可视化不会做🤣
